### ISSUE TITLE
zm & za fold all code

### ISSUE THREAD

**Issue by UNIONDONG** [kevinhwang91/nvim-ufo#161]
### Neovim version (nvim -v | head -n1)

NVIM v0.10.0-dev

### Operating system/version

ubuntu  5.10.16.3

### How to reproduce the issue

za & zm  fold all code ，why？

config ：

![image](https://github.com/kevinhwang91/nvim-ufo/assets/35584433/47d00d3c-aa00-41cd-8f54-8b767241addc)

### Expected behavior

![image](https://github.com/kevinhwang91/nvim-ufo/assets/35584433/92351acf-6cc1-4820-b3f9-cb86fac2c1f6)

### Actual behavior

normal work，only code if while and so on ...

**Comment by kevinhwang91** [comment]
Are you still using neovim?

**Comment by kevinhwang91** [comment]
stale

**Comment by mehalter** [comment]
I also get this as well. Looking at the recommended mappings:

```lua
vim.keymap.set('n', 'zR', require('ufo').openAllFolds)
vim.keymap.set('n', 'zM', require('ufo').closeAllFolds)
vim.keymap.set('n', 'zr', require('ufo').openFoldsExceptKinds)
vim.keymap.set('n', 'zm', require('ufo').closeFoldsWith) -- closeAllFolds == closeFoldsWith(0)
```

It seems that the recommended keybindings for `zR`/`zM` and `zr`/`zm` just do the same things:

`zR` -> `openAllFolds()` -> `openFoldsExceptKinds()`
`zR` -> `openFoldsExceptKinds()`

`zM` -> `closeAllFolds()` -> `closeFoldsWith(0)`
`zm` -> `closeFoldsWith()` -> `closeFoldsWith(0)` (when just pressing `zm` without a number, `vim.v.count = 0`)

This leads to the behavior where `zr` == `zR` and `zm` == `zM` so there actually are no "fold more" or "fold less" operations, they are just doing the same behavvior as the "open all folds" and "close all folds".

Could this be reopened until the functions get fixed? `zm` and `zr` should incrememntally open and close more and more folds as you press them rather than always closing/opening all folds.

If you would rather me open a new issue then I can do that as well. Thanks for all your work on this project!

**Comment by jimrybarski** [comment]
I was having this same issue, though it was just caused by not setting a provider. The config at the top had its provider commented out, maybe that was the issue?

```
require('ufo').setup({
    provider_selector = function(bufnr, filetype, buftype)
        return {'treesitter', 'indent'}
    end
})
```
