### ISSUE TITLE
Remove nesting numbers near the linenumbers

### ISSUE THREAD

**Issue by MrBrN197** [kevinhwang91/nvim-ufo#172]
### Neovim version (nvim -v | head -n1)

v0.10.0-dev-1353+gaa62579a6

### Operating system/version

Ubuntu 22

### How to reproduce the issue

`cat mini.lua`
```lua
-- Use Vim packages install the plugin, also work with some plugins manager such as packer.nvim
vim.o.packpath = '~/.local/share/nvim/site'
vim.cmd('packadd promise-async')
vim.cmd('packadd nvim-ufo')

-- Setting
vim.o.foldcolumn = '1'
vim.o.foldlevel = 99
vim.o.foldlevelstart = -1
vim.o.foldenable = true

local ufo = require('ufo')
ufo.setup()
vim.keymap.set('n', 'zR', ufo.openAllFolds)
vim.keymap.set('n', 'zM', ufo.closeAllFolds)
```
`nvim --clean +'so mini.lua'`

1.
2.
3.
...

### Expected behavior

strange numbers on the number line  numbers on the column line

### Actual behavior

strange numbers on the column line.

how do I get rid of this numbers on the side that show the level of nesting.

![image](https://github.com/kevinhwang91/nvim-ufo/assets/18730106/3760f8cf-92a9-44a2-9827-c6880628e3aa)

**Comment by xiyaowong** [comment]
https://github.com/kevinhwang91/nvim-ufo/issues/4

**Comment by Nullarity** [comment]
And finally, is there a clear answer how to remove these numbers? The link provided didn't help ((

**Comment by rockyzhang24** [comment]
@Nullarity Two ways:
1.  Make a slight modification to the neovim source code and build it by yourself. You may refer to this comment https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1157722074). Note: since neovim 0.9 `src/nvim/screen.c` was refactored to `src/nvim/drawline.c`, so make this change in `drawline.c`.
2. Use another plugin [statuscol.nvim](https://github.com/kevinhwang91/nvim-ufo/issues/4#issuecomment-1157722074).

**Comment by geloman-likes-rust** [comment]
> And finally, is there a clear answer how to remove these numbers? The link provided didn't help ((

I have this workaround and it did fixed the foldcolumn numbers problem.
```lua
vim.o.foldcolumn = 'auto:9'
```
Setting the `foldcolumn` to `auto:9` will auto adjust/resize the width of `foldcolumn` and also remove the foldcolumn random numbers.
