### ISSUE TITLE
Use LSP provider if available or tree-sitter as fallback

### ISSUE THREAD

**Issue by gbrlsnchs** [kevinhwang91/nvim-ufo#63]
### Feature description

I've seen in the examples that you can either use LSP plus regular fallback or tree-sitter plus regular fallback, but can you use LSP when available, then tree-sitter as the fallback? Some filetypes don't have such LSP support but do have tree-sitter support.

### Describe the solution you'd like

Use LSP provider if available, otherwise fall back to tree-sitter provider and only if none is available, then fall back to the default one.

**Comment by kevinhwang91** [comment]
TLDR;
https://github.com/kevinhwang91/nvim-ufo/blob/40bf50c8ba5fb82a30611ec54b17048de3aad72a/doc/example.lua#L24-L49



`main` provider may throw `UfoFallbackException` error to wake up `fallback` provider. If you want to use `lsp->treesitter->indent` chain, you must add the customized provider yourself. ufo has given an example.

Never consider adding this example to README because in I haven't seen a fallback chain for a client to request servers that I think is fragile.
