### ISSUE TITLE
Support inkarkat/vim-mark

### ISSUE THREAD

**Issue by skt041959** [kevinhwang91/nvim-ufo#76]
### Feature description

This plugin [vim-mark](https://github.com/inkarkat/vim-mark) can highlight multiple words with different colors.
![image](https://user-images.githubusercontent.com/604451/188828578-abea335c-1af4-48f8-9415-32640b508784.png)

But the highlight is not honored by ufo in the folded text.
![image](https://user-images.githubusercontent.com/604451/188829458-2664b2a2-054a-4bd3-8c24-f1b02c20b36d.png)

### Describe the solution you'd like

Maybe Ufo can cache the result of `getmatches()`, and apply to the folded text

### Additional context

Thanks Kevin for creating Ufo, It's very amazing!

**Comment by kevinhwang91** [comment]
It's hard to compatible vim's `:match` system.

There're some limitations to capture highlighting in ufo:
1. ufo only captures the highlight group with `fg` attribute, but from the image you provided, I'm afraid that it doesn't contain `fg` attribute;
2. In mixed capturing mode, the priority is unconfirmed because Neovim has two priority systems for highlighting;

You can customize the `fold_virt_text_handler` to implement this feature, I know this workaround is not perfect. You must call `getmatches` to get the matches and inject the target match into the new virt text.
